[package]
name = "marioprompt"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
indoc = { version = "2.0.5" }
