---
name: Default
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustc --version
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt -- --check
      - run: cargo check --locked
      - run: cargo clippy --locked
      - run: cargo test --locked
      - run: cargo build --locked --release --verbose
      - run: ./target/release/mp
